spring.application.name: central-config-service

server:
  port: 8888
  
spring:
  profiles:
    active:
    - native
    - vault
    
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:c:/configrepo
        
        vault:
          host: localhost
          port: 8200
          kv-version: 2

    vault:
      host: localhost
      port: 8200
      kv:
        enabled: true
        backend: secret/data
        default-context: customer-microservice
        #backend-version: 2