services:
  #service 1: setting up mysql database
  mysqldb:
   image: mysql:8.0.39
   container_name: mysql-service
   environment:
    - MYSQL_ROOT_PASSWORD=passw0rd
   ports:
    - "3307:3306"
   restart: always
  
  #service 2: setting up our spring boot app
  product-microservice:
   image: product-microservice-img
   container_name: product-microservice
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "9001:8001"
   restart: always
   depends_on:
    - mysqldb
   environment:
    SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql-service:3306/training?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "passw0rd"
     }'