FROM openjdk:17-alpine
#RUN apt update && install openjdk-17-jdk -y
COPY 06.discovery-and-registry-service/target/06.discovery-and-registry-service-0.0.1-SNAPSHOT.jar app.jar
CMD java -jar app.jar
