spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: customer-api
          #uri: http://localhost:8003
          uri: lb://customer-microservice
          predicates:
          - Path=/customer/**
        - id: productcomposite-api
          #uri: http://localhost:8000
          uri: lb://productcomposite-microservice
          predicates:
          - Path=/product-info/**
          - Header=Api-Key, ^[a-zA-Z0-9]+$
      
server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  