spring.application.name: customer-microservice

spring:
  config:
    import:
    - "configserver:"
    
  cloud:
    config:
      uri:
      - http://localhost:8888
      
    vault:
      token: hvs.s0M2Tg2xUXN2L7JbGYXErHef